/// <reference types="vite/client" />
/// <reference types="@sigx/vite/client" />

// Generated by the ui build (`dist/ds/register.d.ts`); CI typechecks before it builds, so the
// ambient shorthand stands in until the real augmentation resolves.
declare module '@agentic/ui/register';
