/** Routing — execution routing: environment selection, offline policy, capacity queue, never a silent switch (architecture §7; EXE-09/11/12, AST-05). */
export { answerTurnId, defineRoutingActor, MACHINE_LOST_CODE, MACHINE_LOST_MS, MACHINE_LOST_REMINDER, PROJECT_MISSING_CODE, ROUTER, SESSION_RESET_CODE, type AnswerDelivery, type RoutingActor, type RoutingView } from './actor.js';
export { DEFAULT_TOOL_FAMILIES, FEATURE_MESSAGE_MAX, featureSettings, featureTools, machineFs, noDaemonFs, PLAN_TOOL_NAMES, runFeatureHooks, skippedToolsNote, withFeatureTools, type FeatureHooksInput, type FeatureHooksOutcome, type FeatureTools, type FsMachineClient, type MachineFsOptions, type SkippedToolFamily, type ToolFamilies } from './features.js';
export { CHAT_FILE_READ, FILE_UNAVAILABLE, fileNote, hydrateChatFiles, readChatFile, withChatFileRead, type FileAccess, type HydrateOptions } from './files.js';
export { callPlatformConnector, connectorCategory, connectorCredentials, ConnectorCredentialsError, connectorPolicy, daemonConnectors, openSessionConnectors, platformConnectorTools, PlatformConnectorError, TOOLS_REVOKED_REASON, withWorkspaceRules, workspaceToolRules, type CallPlatformConnectorInput, type PlatformConnectorToolsInput, type ConnectorCredentialsInput, type DaemonConnectorPlacement, type ConnectorOpenContext, type ConnectorOpenInput, type ConnectorOpener, type ConnectorTool, type OpenSessionConnectorsInput, type OpenedConnector, type SessionConnectors, type UnavailableConnector } from './connectors.js';
export { anthropicApiRuntime, createSessionFactory, resolveRuntime, withInstanceRuntimes, NO_API_KEY_CODE, PLUGIN_DISABLED_CODE, UNKNOWN_RUNTIME_CODE, type AnthropicApiRuntimeOptions, type InstanceRuntimes, type RuntimeCatalogue, type RuntimeImpl, type RuntimePluginAccess, type SessionFactoryOptions } from './factory.js';
export { ROUTING_TYPE, parseRoutingKey, routingKey } from './key.js';
export { createEnvironmentProbe, locateEnvironment, readMachine, type EnvironmentProbeOptions, type LocatedEnvironment } from './locate.js';
export type { RoutingPorts } from './ports.js';
export { initialRoutingState, type Route, type RouteStatus, type RoutingState } from './state.js';
export { AnswerDeliveryError, answerContract, answerObjective, answerPostText, answerPrompt, answerTaskId, createAnswerFollowUp, type AnswerFollowUpOptions, type AnswerStep } from './answers.js';
export { createToolCallPort, type ToolCallPortOptions } from './tool-call.js';
export { agentChatKey, answerText, ASK_QUICK_WAIT_MS, createActorToolPorts, DELEGATE_WAIT_MS, type ActorToolPortsOptions, type AgentPrincipal } from './tools.js';
