#!/usr/bin/env node
/**
 * `pnpm dev` — one command to the REAL app locally (#143, USR-02 / OPS-09):
 * the Worker on `wrangler dev` (actors on simulated Durable Objects, R2
 * simulated) at http://localhost:8787, signed in with one click.
 *
 *   1. `apps/web/.dev.vars` missing → generate it: random `SESSION_SECRET`,
 *      `WORKSPACE_KEK`, `AGENTIC_DEV_LOGIN`; `ANTHROPIC_API_KEY` copied from
 *      the environment when present, else a commented placeholder and a
 *      warning (agents fail `no-api-key` until it is set).
 *   2. `pnpm build` when `apps/web/dist` is missing or older than any file
 *      under `apps/web/src` or `packages/<pkg>/src` (a cheap mtime check), or
 *      always with `--rebuild`.
 *   3. `wrangler dev` in the foreground, after printing the dev-login link
 *      `http://localhost:8787/auth/dev-login?token=<AGENTIC_DEV_LOGIN>`.
 *
 * Usage:
 *   pnpm dev                 # the Worker, as above
 *   pnpm dev --rebuild       # force the build first
 *   pnpm dev --port 8788     # another port (the link follows)
 *   pnpm dev:mock            # the Vite mock server instead (no actors, no secrets)
 *
 * Node only, Windows and Linux: `pnpm` runs through the pnpm that started this
 * script (`npm_execpath`), wrangler through its own bin under `apps/web`.
 */
import { spawn, spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const WEB_DIR = path.join(REPO_ROOT, 'apps', 'web');
export const DEV_VARS = path.join(WEB_DIR, '.dev.vars');
export const DEFAULT_PORT = 8787;

/** Directories never walked for the mtime check. */
const SKIP_DIRS = new Set(['node_modules', 'dist', '.wrangler', '.git', 'test-results', 'playwright-report', 'coverage']);

// ── args ───────────────────────────────────────────────────────────────────

/** `--rebuild`, `--mock`, `--port <n>`, `--help`; anything else is an error. */
export function parseArgs(argv) {
    const flags = { rebuild: false, mock: false, help: false, port: DEFAULT_PORT };
    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        if (a === '--rebuild') flags.rebuild = true;
        else if (a === '--mock') flags.mock = true;
        else if (a === '--help' || a === '-h') flags.help = true;
        else if (a === '--port') {
            const n = Number(argv[++i]);
            if (!Number.isInteger(n) || n <= 0) throw new Error(`--port needs a positive integer, got '${argv[i]}'`);
            flags.port = n;
        } else if (a.startsWith('--port=')) {
            const n = Number(a.slice('--port='.length));
            if (!Number.isInteger(n) || n <= 0) throw new Error(`--port needs a positive integer, got '${a.slice('--port='.length)}'`);
            flags.port = n;
        } else throw new Error(`unknown argument '${a}' (see: node scripts/dev.mjs --help)`);
    }
    return flags;
}

// ── .dev.vars ──────────────────────────────────────────────────────────────

/** `KEY=VALUE` per line; `#` comments and blanks skipped; surrounding quotes dropped. */
export function parseDevVars(text) {
    const vars = {};
    for (const raw of text.split(/\r?\n/)) {
        const line = raw.trim();
        if (!line || line.startsWith('#')) continue;
        const eq = line.indexOf('=');
        if (eq <= 0) continue;
        const key = line.slice(0, eq).trim();
        let value = line.slice(eq + 1).trim();
        if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1);
        vars[key] = value;
    }
    return vars;
}

/** URL-safe random text of `chars` characters (base64url of enough bytes). */
const randomText = (random, chars) => random(Math.ceil((chars * 3) / 4)).toString('base64url').slice(0, chars);

/**
 * The file `pnpm dev` writes on first run. `anthropicApiKey` (the process
 * env's) lands as the real line when present, else as a commented
 * placeholder. `random` is injectable so a test can pin the output.
 */
export function renderDevVars({ anthropicApiKey = '', random = randomBytes } = {}) {
    const sessionSecret = randomText(random, 48);
    const kek = random(32).toString('base64');
    const devLogin = randomText(random, 32);
    const key = anthropicApiKey.trim();
    const lines = [
        '# Local secrets for `wrangler dev` (apps/web). Generated by `pnpm dev` (scripts/dev.mjs); never committed.',
        '# Regenerate by deleting this file. See docs/runbook.md §4.',
        '',
        '# ≥ 32 chars — signs sessions, OAuth transients and agent tokens.',
        `SESSION_SECRET=${sessionSecret}`,
        '',
        '# base64 of 32 random bytes — AES-GCM key for API keys stored in the Registry.',
        `WORKSPACE_KEK=${kek}`,
        '',
        '# ≥ 16 chars — enables /auth/dev-login (the "Dev login" button, the link `pnpm dev` prints). Never set on production.',
        `AGENTIC_DEV_LOGIN=${devLogin}`,
        '',
        '# The key the anthropic-api runtime uses. Without it an agent task fails `no-api-key`.',
        key ? `ANTHROPIC_API_KEY=${key}` : '# ANTHROPIC_API_KEY=sk-ant-...',
        '',
        '# Optional — a GitHub OAuth app whose callback is http://localhost:8787/auth/callback enables "Sign in with GitHub".',
        '# GITHUB_CLIENT_ID=',
        '# GITHUB_CLIENT_SECRET=',
        ''
    ];
    return { text: lines.join('\n'), anthropic: key ? 'env' : 'placeholder', vars: { SESSION_SECRET: sessionSecret, WORKSPACE_KEK: kek, AGENTIC_DEV_LOGIN: devLogin, ...(key ? { ANTHROPIC_API_KEY: key } : {}) } };
}

/**
 * Create `file` when missing (from `env.ANTHROPIC_API_KEY`), read it
 * otherwise. Returns the parsed vars and what happened, for the log.
 */
export function ensureDevVars(file, env = process.env, { random = randomBytes } = {}) {
    if (existsSync(file)) {
        const vars = parseDevVars(readFileSync(file, 'utf8'));
        return { created: false, vars, anthropic: vars.ANTHROPIC_API_KEY ? 'file' : env.ANTHROPIC_API_KEY ? 'env-only' : 'missing' };
    }
    const rendered = renderDevVars({ anthropicApiKey: env.ANTHROPIC_API_KEY ?? '', random });
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileSync(file, rendered.text, { encoding: 'utf8', mode: 0o600 });
    return { created: true, vars: rendered.vars, anthropic: rendered.anthropic };
}

/** The one-click link: the form prefills the secret from `?token=` on localhost only. */
export const devLoginLink = (vars, port = DEFAULT_PORT) => (vars.AGENTIC_DEV_LOGIN ? `http://localhost:${port}/auth/dev-login?token=${encodeURIComponent(vars.AGENTIC_DEV_LOGIN)}` : `http://localhost:${port}/auth/dev-login`);

// ── build freshness ────────────────────────────────────────────────────────

/** The newest mtime (ms) of any file under `dir`, skipping build and dependency folders; 0 when `dir` is missing. */
export function newestMtimeMs(dir) {
    let newest = 0;
    const walk = (d) => {
        let entries;
        try {
            entries = readdirSync(d, { withFileTypes: true });
        } catch {
            return;
        }
        for (const e of entries) {
            if (e.isDirectory()) {
                if (!SKIP_DIRS.has(e.name)) walk(path.join(d, e.name));
            } else if (e.isFile()) {
                try {
                    const m = statSync(path.join(d, e.name)).mtimeMs;
                    if (m > newest) newest = m;
                } catch {
                    /* raced away; ignore */
                }
            }
        }
    };
    walk(dir);
    return newest;
}

/** `apps/web/src` and every `packages/<name>/src` that exists. */
export function sourceDirs(repoRoot = REPO_ROOT) {
    const dirs = [path.join(repoRoot, 'apps', 'web', 'src')];
    const packages = path.join(repoRoot, 'packages');
    if (existsSync(packages)) {
        for (const e of readdirSync(packages, { withFileTypes: true })) {
            if (!e.isDirectory()) continue;
            const src = path.join(packages, e.name, 'src');
            if (existsSync(src)) dirs.push(src);
        }
    }
    return dirs;
}

/**
 * Whether `pnpm build` must run: the dist's entry is missing, or any source
 * file is newer than the newest file in `distDir`. `{ build, reason }`.
 */
export function needsBuild({ distDir, sources, entry = path.join('server', 'entry.cloudflare.js') }) {
    if (!existsSync(path.join(distDir, entry))) return { build: true, reason: `${path.relative(REPO_ROOT, distDir) || distDir} has no ${entry}` };
    const built = newestMtimeMs(distDir);
    for (const src of sources) {
        const newest = newestMtimeMs(src);
        if (newest > built) return { build: true, reason: `${path.relative(REPO_ROOT, src) || src} changed after the last build` };
    }
    return { build: false, reason: 'dist is newer than every source file' };
}

// ── processes ──────────────────────────────────────────────────────────────

/**
 * How to run `pnpm <args>` without a shell: through the pnpm entry that
 * started this script when there is one (`npm_execpath` — a JS file on
 * every platform), else `pnpm` through the shell as `scripts/worktree.mjs` does.
 */
export function pnpmCommand(args, env = process.env) {
    const exec = env.npm_execpath;
    if (exec && /\.(c|m)?js$/i.test(exec) && existsSync(exec)) return { file: process.execPath, args: [exec, ...args], shell: false };
    return { file: 'pnpm', args, shell: true };
}

/** wrangler's own bin under `apps/web`, run with this Node. */
export function wranglerCommand(args, webDir = WEB_DIR) {
    const bin = path.join(webDir, 'node_modules', 'wrangler', 'bin', 'wrangler.js');
    if (!existsSync(bin)) throw new Error(`wrangler is not installed under ${path.relative(REPO_ROOT, webDir)} — run pnpm install first`);
    return { file: process.execPath, args: [bin, ...args], shell: false };
}

/**
 * Stop `child` and everything under it. On Windows `child.kill()` ends only
 * the one process — wrangler's workerd would keep port 8787 — so the tree
 * goes through `taskkill /T`; elsewhere the child gets SIGTERM and wrangler
 * takes its own children down.
 */
function killTree(child) {
    if (child.exitCode !== null || child.signalCode !== null) return;
    if (process.platform === 'win32') spawnSync('taskkill', ['/pid', String(child.pid), '/T', '/F'], { stdio: 'ignore', windowsHide: true });
    else child.kill('SIGTERM');
}

/** Run a command in the foreground; resolves with its exit code. Ctrl+C (or this process ending) stops the child tree first. */
function run({ file, args, shell }, { cwd = REPO_ROOT, env = process.env } = {}) {
    return new Promise((resolve, reject) => {
        const child = spawn(file, args, { cwd, env, stdio: 'inherit', shell, windowsHide: true });
        const stop = () => killTree(child);
        process.on('SIGINT', stop);
        process.on('SIGTERM', stop);
        process.on('exit', stop);
        const done = () => {
            process.off('SIGINT', stop);
            process.off('SIGTERM', stop);
            process.off('exit', stop);
        };
        child.on('error', (err) => {
            done();
            reject(err);
        });
        child.on('exit', (code, signal) => {
            done();
            resolve(code ?? (signal ? 130 : 1));
        });
    });
}

// ── main ───────────────────────────────────────────────────────────────────

const log = (msg) => console.log(`[dev] ${msg}`);
const warn = (msg) => console.warn(`[dev] WARNING: ${msg}`);

const HELP = `pnpm dev [--rebuild] [--port <n>]   the Worker on wrangler dev (default port ${DEFAULT_PORT})
pnpm dev:mock                        the Vite mock server (apps/web/server.mjs, port 3000)

Generates apps/web/.dev.vars on first run, builds when the sources are newer than
apps/web/dist, then starts wrangler dev and prints the dev-login link.`;

export async function main(argv = process.argv.slice(2)) {
    let flags;
    try {
        flags = parseArgs(argv);
    } catch (e) {
        console.error(`[dev] ${e.message}`);
        return 2;
    }
    if (flags.help) {
        console.log(HELP);
        return 0;
    }

    if (flags.mock) {
        log('mock mode: the Vite dev server over the design track\'s workspace (no actors, no secrets)');
        return run({ file: process.execPath, args: [path.join(WEB_DIR, 'server.mjs')], shell: false }, { cwd: WEB_DIR });
    }

    // 1. secrets
    const dv = ensureDevVars(DEV_VARS);
    const rel = path.relative(REPO_ROOT, DEV_VARS);
    if (dv.created) {
        log(`created ${rel} with a random SESSION_SECRET, WORKSPACE_KEK and AGENTIC_DEV_LOGIN`);
        if (dv.anthropic === 'env') log(`copied ANTHROPIC_API_KEY from your environment into ${rel}`);
    } else {
        log(`using ${rel}`);
    }
    if (dv.anthropic === 'placeholder' || dv.anthropic === 'missing') {
        warn(`ANTHROPIC_API_KEY is not set in ${rel}: agents on the anthropic-api runtime will fail with no-api-key until you add it (then restart pnpm dev)`);
    } else if (dv.anthropic === 'env-only') {
        warn(`ANTHROPIC_API_KEY is in your environment but not in ${rel} — wrangler dev reads only the file; add the line there (then restart pnpm dev)`);
    }
    if (!dv.vars.AGENTIC_DEV_LOGIN || dv.vars.AGENTIC_DEV_LOGIN.length < 16) warn(`AGENTIC_DEV_LOGIN is missing or shorter than 16 chars in ${rel}: the dev login will not be mounted`);
    if (!dv.vars.SESSION_SECRET || dv.vars.SESSION_SECRET.length < 32) warn(`SESSION_SECRET is missing or shorter than 32 chars in ${rel}: every request will be anonymous`);

    // 2. build
    const distDir = path.join(WEB_DIR, 'dist');
    const check = flags.rebuild ? { build: true, reason: '--rebuild' } : needsBuild({ distDir, sources: sourceDirs() });
    if (check.build) {
        log(`building (${check.reason}) …`);
        const code = await run(pnpmCommand(['build']));
        if (code !== 0) {
            console.error(`[dev] build failed (exit ${code})`);
            return code;
        }
    } else {
        log(`build is up to date (${check.reason}); pass --rebuild to force one`);
    }

    // 3. wrangler dev
    const link = devLoginLink(dv.vars, flags.port);
    log('starting wrangler dev — once it says Ready, sign in with one click:');
    log('');
    log(`    ${link}`);
    log('');
    log(`then open http://localhost:${flags.port}/agents. Ctrl+C stops it; after a source change run pnpm dev again (it rebuilds).`);
    const args = ['dev'];
    if (flags.port !== DEFAULT_PORT) args.push('--port', String(flags.port));
    return run(wranglerCommand(args), { cwd: WEB_DIR });
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    main().then(
        (code) => {
            process.exitCode = code;
        },
        (err) => {
            console.error(`[dev] ${err?.message ?? err}`);
            process.exitCode = 1;
        }
    );
}
