/** Machine actor — a paired daemon's record, its hibernatable socket protocol, capacity queue, pending replies, folder requests and environment requests (architecture §4 Machine, §5b). */
export type { MachineSocketPort, ToolCallInput, ToolCallPort, MachinePorts } from './ports.js';
export { ToolCallError } from './ports.js';
export type { MachineOs, HostedSession, QueuedSession, PendingCommand, FsRequestRecord, EnvRequestRecord, HistoryRequestRecord, SessionClosure, MachineState, CapacityView, MachineDraining, PendingUpdate, UpdateOutcome, AvailableUpdate, MachineUpdateState, HarnessOp, HarnessRequestRecord, AvailableHarness } from './state.js';
export { MACHINE_STATE_VERSION, MAX_CLOSURES, MAX_FS_REQUESTS, FS_RESULT_TTL_MS, MAX_ENV_REQUESTS, ENV_RESULT_TTL_MS, MAX_HISTORY_REQUESTS, HISTORY_RESULT_TTL_MS, MAX_HARNESS_REQUESTS, HARNESS_RESULT_TTL_MS, initialMachineState, machineKey, parseMachineKey, activeIn, freeSlots, hostedIn, isIdle, runningIn, pruneQuota, pruneTelemetry } from './state.js';
export type { PairInfo, PairedMachine, OpenSessionResult, OpenSessionOptions, SocketMessageResult, MachineView, MachineActor, EnvironmentDoctorView, MachineDoctorView, FsRequested, FsResultView, EnvRequested, EnvResultView, EnvironmentQuotaView, MachineQuotaView, HistoryRequested, HistoryResultView, MachineUpdateView, UpdateRequestInput, HarnessRequestInput, HarnessRequested, HarnessResultView, LoginRequested, LoginStateView } from './actor.js';
export { usageLimitsOf } from './usage.js';
export { defineMachineActor, toAgentCapabilities, LIVENESS, DEFAULT_HEARTBEAT_WINDOW_MS, DEFAULT_COMMAND_TIMEOUT_MS, DEFAULT_FS_TIMEOUT_MS, DEFAULT_ENV_TIMEOUT_MS, DEFAULT_HISTORY_TIMEOUT_MS, MACHINE_OFFLINE_CODE, UPDATE_COMPARE_EVERY_MS, HARNESS_DEADLINE_MS } from './actor.js';
export { SYSTEM_UPDATES, DEFAULT_DRAIN_TIMEOUT_MS, MAX_DRAIN_TIMEOUT_MS, UPDATE_DEADLINE_GRACE_MS, CRASH_LOOP_RESTARTS, CRASH_LOOP_WINDOW_MS, checkChannel, checkUpdatePolicy, effectiveUpdates, inWindow, nextAutoUpdate } from './update.js';
export { machineHistorySource } from './history.js';
